resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/16.yaml

packages:
- .

extra-deps:
- morpheus-graphql-client-0.18.0
- morpheus-graphql-code-gen-0.18.0
- morpheus-graphql-core-0.18.0
